version: '3'
services: 
  web-go:
    build: .
    ports: 
      - 80:8080
    volumes: 
      - .:/go/src/github.com/cloudydong/testgo
    restart: always
    depends_on: 
      - "db-postgres"
  db-postgres:
    image: postgres
    ports: 
      - "5432:5432"
    restart: always
    volumes: 
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
  # pgadmin-compose:
  #   image: dpage/pgadmin4
  #   environment: 
  #     PGADMIN_DEFAULT_EMAIL: "test@gmail.com"
  #     PGADMIN_DEFAULT_PASSWORD: "test123!"
  #   ports: 
  #     - "16543:80"
  #   depends_on: 
  #     - database